Use custom exception to report compilation failure in Birk. Previously used `sun.tools.java.CompilerError` has wrong semantics, is proprietary and causes `NoClassDefFoundError` when running on JRE.